---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-gitops
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/santosh-gh/my-gitops
